### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by seansassen** [kellerza/hassio-sma-em#15]
Hi there, 

Getting the following error when trying to install the add-on, any guidance would be appreciated.

Thanks.

```
_**Failed to install add-on**

The command '/bin/ash -o pipefail -c pip3 install --no-cache-dir paho-mqtt~=1.5.0 attrs requests~=2.24.0 icecream' returned a non-zero code: 1_
```

**Comment by seansassen** [comment]
@kellerza any idea?

PS. Also from RSA :)

**Comment by kellerza** [comment]
Hey @seansassen sorry was a bit preoccupied mountain biking over your mountains this weekend.

The error does not say much, but likely just connectivity/DNS related. Do you have a static IP on your hass os? Do you use adguard/pihole etc?

**Comment by seansassen** [comment]
No problem, that's obviously a more important hobby.

I do have a static ip, and I did have adguard installed - just tried to deactivate it, but still got the same error.

**Comment by kellerza** [comment]
Can you check the "supervisors" logs and see if you get any more information? What version of the supervisor are you running? "stable channel"?

In [this](https://community.home-assistant.io/t/sma-energy-meter-in-home-assistant/47482/156) chat someone had a similar problem, but was DNS related. That might also be a good place to check

**Comment by seansassen** [comment]
`Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError:
[Errno 1] Operation not permitted`

**Comment by seansassen** [comment]
Running supervisor-2021.10.8, but will look into the other chat and see if anything I can find.

Thanks for all your help.

**Comment by kellerza** [comment]
From the community there is also this - https://community.home-assistant.io/t/2021-7-a-new-entity-trigger-ids-and-script-debugging/320556/50?u=kellerza - expand the "Replies" on this topic

**Comment by seansassen** [comment]
All resolved, thanks for your help @kellerza
