### ISSUE TITLE
consume and consumecounter have wrong device_class

### ISSUE THREAD

**Issue by gabrio79** [kellerza/hassio-sma-em#20]
sensor.s1consume has unit VA which is unsupported for device_class energy ---> must have device_class: apparent_power
sensor.s3consume has unit VA which is unsupported for device_class energy
sensor.s2consume has unit VA which is unsupported for device_class energy
sensor.s2consumecounter has unit kVAh which is unsupported for device_class energy
sensor.s3consumecounter has unit kVAh which is unsupported for device_class energy

**Comment by kellerza** [comment]
Thanks @gabrio79! 
Any idea if there is a device_class that could match `kVah`, or simply no device class / `None`?

**Comment by gabrio79** [comment]
I searched but i dis't applicabile class foundee, i can suggest you to open
an issue on ha-core? in the midtime, no class or remain energy

Il Gio 25 Ago 2022, 21:05 Johann Kellerman ***@***.***> ha
scritto:

**Comment by gabrio79** [comment]
Is you device accurate? I notated big differces betwen shm2 and fiscale
Meter measure... I opened a ticket on sma support... But for them no
issue... Have you ever checked?

Il Gio 25 Ago 2022, 21:23 Gabrio ***@***.***> ha scritto:

**Comment by alexfiftyfour** [comment]
This is the device class list.
https://www.home-assistant.io/integrations/sensor/

I have a similar problem with the current.

**Comment by kellerza** [comment]
Please try the -dev add onhttps://github.com/kellerza/hassio-sma-em/blob/main/sma-em-dev/Dockerfile#L4
