### ISSUE TITLE
Could this add-on be used without an MQTT server?

### ISSUE THREAD

**Issue by TheAssassin** [kellerza/hassio-sma-em#36]
The documentation hint towards the requirement for an MQTT server, which is needed to ingest the sensor data into Home Assistant (and also enable auto-discovery). Given that this is an "add-on" to Home Assistant, I could imagine that the data could be passed to Home Assistant directly.

Is it possible to remove this dependency? I do have Mosquitto running anyway, so I'm not affected by this, but then again, it doesn't make a lot of sense to me. However, I don't know very much about Home Assistant's add-on/plugin system, and this could be an entirely normal thing to do.

Please note that I do appreciate the MQTT integration which I could potentially use with other software, e.g., EVCC. If there is an alternative way to pass the messages, this should be retained as an optional feature. As far as I can see, the SMA-EM scripts support that anyway and you seem to be using that, too.

Edit: I forgot to include this: thank you for providing this plugin in the first place. Users of SMA energy meters can enjoy live energy comsumption/supply data along with long-term statistics and use those to optimize their power use. It's much easier to setup than, e.g., the original SMA-EM project with MQTT.

**Comment by kellerza** [comment]
An addon is an isolated Docker container. So you need some way to communicate.

ESPhome has an alternative to MQTT, but no plans to do anything like this
