### ISSUE TITLE
Advice for manual installation

### ISSUE THREAD

**Issue by DeltaTango69** [kellerza/hassio-sma-em#41]
Hi,

I am using Homeassistant with docker compose under wsl2. I have no option to intall addons. So can you please give me advice for manual installation? I have tried to copy the "hassio-sma-em.main" under custom_components but i am not able to see the integration in home assistant.

**Comment by kellerza** [comment]
You will have to clne and build the docker install yourelf - try looking at https://kellerza.github.io/sunsynk/guide/standalone-deployment#run-standalone-using-docker-compose (it's for another addon, but same concept)
